### ISSUE TITLE
Input 'bytes' of 'DecodeRaw' Op has type float32 that does not match expected type of string.

### ISSUE THREAD

**Issue by qizhao1** [Kyubyong/deepvoice3#16]
Hi Kyubyong Park,

Much thanks for the wonderful job.
I used python2.7, tensorflow 1.4.1, when I run train.py, there is a error:

File "train.py", line 103, in <module>
    g = Graph(); print("Training Graph loaded")
  File "train.py", line 34, in __init__
    self.x, self.y1, self.y2, self.z, self.num_batch = get_batch()
  File "/home/zqi/zq/TTS/deepvoice3/data_load.py", line 123, in get_batch
    text = tf.decode_raw(text, tf.int32) # (None,)

the erroe is : Input 'bytes' of 'DecodeRaw' Op has type float32 that does not match expected type of string.

**Comment by Tortoise17** [comment]
I also have same issue. Can you guide how to resolve?

**Comment by huanli2012** [comment]
Replace
`text = tf.decode_raw(text, tf.int32) `
with
`text = tf.cast(text, tf.int32) `.
